kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: nginx-ingress
subjects:
  - kind: ServiceAccount
    namespace: nginx-ingress
    name: nginx-ingress
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
